export const wagrDuelEscrowAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'initialOwner', type: 'address', internalType: 'address' },
      { name: 'initialResolver', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'acceptDuel',
    inputs: [{ name: 'duelId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'cancelOpenDuel',
    inputs: [{ name: 'duelId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimPayout',
    inputs: [{ name: 'duelId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimRefund',
    inputs: [{ name: 'duelId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createDuel',
    inputs: [
      { name: 'creatorSide', type: 'uint8', internalType: 'enum WagrDuelEscrow.Side' },
      { name: 'expiry', type: 'uint256', internalType: 'uint256' },
      { name: 'metadataHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: 'duelId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'duels',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'creator', type: 'address', internalType: 'address' },
      { name: 'counterparty', type: 'address', internalType: 'address' },
      { name: 'creatorSide', type: 'uint8', internalType: 'enum WagrDuelEscrow.Side' },
      { name: 'stakeAmount', type: 'uint256', internalType: 'uint256' },
      { name: 'expiry', type: 'uint256', internalType: 'uint256' },
      { name: 'metadataHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'status', type: 'uint8', internalType: 'enum WagrDuelEscrow.DuelStatus' },
      { name: 'verdict', type: 'uint8', internalType: 'enum WagrDuelEscrow.Verdict' },
      { name: 'creatorClaimed', type: 'bool', internalType: 'bool' },
      { name: 'counterpartyClaimed', type: 'bool', internalType: 'bool' },
      { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
      { name: 'acceptedAt', type: 'uint256', internalType: 'uint256' },
      { name: 'resolvedAt', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'markResolutionRequested',
    inputs: [{ name: 'duelId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'nextDuelId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'resolver',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'submitVerdict',
    inputs: [
      { name: 'duelId', type: 'uint256', internalType: 'uint256' },
      { name: 'verdict', type: 'uint8', internalType: 'enum WagrDuelEscrow.Verdict' },
      { name: 'confidenceBps', type: 'uint16', internalType: 'uint16' },
      { name: 'verdictHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateResolver',
    inputs: [{ name: 'newResolver', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'DuelAccepted',
    inputs: [
      { name: 'duelId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'counterparty', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DuelCreated',
    inputs: [
      { name: 'duelId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'creator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'creatorSide', type: 'uint8', indexed: false, internalType: 'enum WagrDuelEscrow.Side' },
      { name: 'stakeAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'expiry', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'metadataHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VerdictSubmitted',
    inputs: [
      { name: 'duelId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'verdict', type: 'uint8', indexed: false, internalType: 'enum WagrDuelEscrow.Verdict' },
      { name: 'confidenceBps', type: 'uint16', indexed: false, internalType: 'uint16' },
      { name: 'verdictHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
] as const

